# config.yml
tests:
- name: Test de inicio de sesi칩n
  description: Validar que un usuario puede iniciar sesi칩n con credenciales v치lidas
  expected: "Inicio de sesi칩n exitoso"
- name: Test de registro
  description: Validar que un nuevo usuario puede registrarse
  expected: "Registro exitoso"

playwright:
  browsers:
  - chromium
  - firefox
  - webkit
