name: Playwright Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3 # Asegúrate de que esta sea la última versión

    - name: Setup Node.js
      uses: actions/setup-node@v3 # Asegúrate de que esta sea la última versión
      with:
        node-version: '20' # Especifica Node.js 20

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
