name: Playwright Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

    steps:
    - name: Check out code
      uses: actions/checkout@v4 # Usar la última versión estable

    - name: Setup Node.js
      uses: actions/setup-node@v4 # Usar la última versión estable
      with:
        node-version: '20' # Especifica la versión 20

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install # Instala los navegadores requeridos por Playwright

    - name: Run tests
      run: npm test # Ahora ejecutará el script que has definido
